[functions.create-document-metadata]
enabled = true
verify_jwt = true
invoke_role = "service_role"
import_map = "./functions/create-document-metadata/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-document-metadata/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-document-metadata/*.html" ]
