import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white dark:bg-gray-800 shadow-sm mb-4">
          <div className="container mx-auto px-6 py-3 flex gap-6">
            <a href="/" className="font-semibold text-blue-600 dark:text-blue-400 hover:underline">ホーム</a>
            <a href="/library" className="font-semibold text-blue-600 dark:text-blue-400 hover:underline">ライブラリ</a>
            <a href="/post" className="font-semibold text-blue-600 dark:text-blue-400 hover:underline">投稿</a>
            <a href="/report" className="font-semibold text-blue-600 dark:text-blue-400 hover:underline">レポート</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
